apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.makeit.it
spec:
  group: makeit.it
  version: v1
  additionalPrinterColumns:
    - JSONPath: .metadata.namespace
      name: Namespace
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
    - JSONPath: .spec.ingressHostName
      name: Hostname
      type: string
    - JSONPath: .spec.ingressPath
      name: Path
      type: string
    - JSONPath: .spec.imageName
      name: Image
      type: string
    - JSONPath: .spec.replicas
      name: Replicas
      type: integer
  names:
    kind: App
    plural: apps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        port:
          type: integer
          minimum: 0
          maximum: 65535
        imageName:
          type: string
        ingressHostName:
          type: string
          pattern: '^([A-Za-z0-9-]{1,63}\.)+[[A-Za-z0-9-]{1,63}$'
        ingressPath:
          type: string
        ingressRewritePath:
          type: string
        ingressTls:
          type: boolean
        ingressAcme:
          type: boolean
        replicas:
          type: integer
          minimum: 1
        parameters:
          type: list
