apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositeapps.makeit.it
spec:
  group: makeit.it
  version: v1
  additionalPrinterColumns:
    - JSONPath: .metadata.namespace
      name: Namespace
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  names:
    kind: CompositeApp
    plural: compositeapps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apps:
          type: list
        ingressTls:
          type: boolean
        ingressAcme:
          type: boolean
        parameters:
          type: list
