apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deploy-operator
  template:
    metadata:
      labels:
        app: k8s-deploy-operator
    spec:
      # serviceAccountName: deploy-operator
      containers:
        - name: server
          image: k8s-deploy-operator
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            # This environment variable enables debugging support for the container.
            # Remove this to disable the debug build.
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y -Djdk.tls.client.protocols=TLSv1.2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
